"use client";
import { useEffect, useRef } from "react";

interface MermaidDiagramProps {
  chart: string;
  id: string;
}

export default function MermaidDiagram({ chart, id }: MermaidDiagramProps) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    async function render() {
      const mermaid = (await import("mermaid")).default;
      mermaid.initialize({
        startOnLoad: false,
        // "base" theme gives full control over themeVariables without dark-theme CSS
        // overrides that silently kill node label contrast.
        theme: "base",
        themeVariables: {
          // --- canvas & backgrounds --- Cloud Atlas palette
          background: "#0f1c20",
          mainBkg: "#11211f",           // default node fill (dark teal-near-black)
          nodeBorder: "#43b5a6",        // teal brand border
          clusterBkg: "#0f1c20",        // subgraph background
          clusterBorder: "#43b5a6",

          // --- node text — must be light on dark fill ---
          primaryColor: "#11211f",      // default node fill (same as mainBkg)
          primaryBorderColor: "#43b5a6",
          primaryTextColor: "#f3ece0",  // light text on dark nodes
          nodeTextColor: "#f3ece0",     // explicit override (Mermaid v11)

          // --- secondary nodes (rhombuses / decision boxes) ---
          secondaryColor: "#132120",
          secondaryBorderColor: "#e0a85e",
          secondaryTextColor: "#f3ece0",

          // --- tertiary nodes (database cylinders etc.) ---
          tertiaryColor: "#0b1417",
          tertiaryBorderColor: "#43b5a6",
          tertiaryTextColor: "#f3ece0",

          // --- edges & labels ---
          lineColor: "#c9c2b6",
          edgeLabelBackground: "#0f1c20",  // avoid transparent bg on arrow labels
          labelTextColor: "#f3ece0",

          // --- cluster/subgraph labels ---
          titleColor: "#43b5a6",

          // --- text sizes ---
          fontSize: "15px",
        },
      });
      if (cancelled || !ref.current) return;
      try {
        const { svg } = await mermaid.render(`mermaid-${id}`, chart);
        if (!cancelled && ref.current) {
          // The SVG is generated by mermaid from static, hardcoded diagram strings
          // in components-data.ts and architecture/page.tsx — there is no user input
          // anywhere in this pipeline.  DOMPurify was stripping <foreignObject>
          // elements (which Mermaid v11 uses for node labels), making all labels
          // invisible.  Since the source is 100% static trusted data, we inject the
          // mermaid SVG directly without sanitization.
          ref.current.innerHTML = svg;
        }
      } catch (e) {
        if (!cancelled && ref.current) {
          // Error message is plain text — set via textContent, never innerHTML.
          const pre = document.createElement("pre");
          pre.className = "text-xs text-red-400 p-4";
          pre.textContent = String(e);
          ref.current.replaceChildren(pre);
        }
      }
    }
    render();
    return () => {
      cancelled = true;
    };
  }, [chart, id]);

  return (
    <div className="mermaid-wrapper">
      <div ref={ref} className="flex justify-center" />
    </div>
  );
}
